// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc-go-course/greet/proto-files/greet.proto

package greatpb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd27a3f1bf22b156, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Greeting) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type GreetRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd27a3f1bf22b156, []int{1}
}

func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (m *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(m, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetResponse) Reset()         { *m = GreetResponse{} }
func (m *GreetResponse) String() string { return proto.CompactTextString(m) }
func (*GreetResponse) ProtoMessage()    {}
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd27a3f1bf22b156, []int{2}
}

func (m *GreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetResponse.Unmarshal(m, b)
}
func (m *GreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetResponse.Marshal(b, m, deterministic)
}
func (m *GreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetResponse.Merge(m, src)
}
func (m *GreetResponse) XXX_Size() int {
	return xxx_messageInfo_GreetResponse.Size(m)
}
func (m *GreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetResponse proto.InternalMessageInfo

func (m *GreetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greet.pb.Greeting")
	proto.RegisterType((*GreetRequest)(nil), "greet.pb.GreetRequest")
	proto.RegisterType((*GreetResponse)(nil), "greet.pb.GreetResponse")
}

func init() {
	proto.RegisterFile("grpc-go-course/greet/proto-files/greet.proto", fileDescriptor_dd27a3f1bf22b156)
}

var fileDescriptor_dd27a3f1bf22b156 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xbf, 0x6f, 0xc3, 0x20,
	0x10, 0x85, 0xe5, 0x0e, 0xae, 0xb9, 0xfe, 0x18, 0x18, 0xaa, 0x4a, 0x55, 0xa5, 0xca, 0x4b, 0x3b,
	0xd4, 0x58, 0x72, 0xf6, 0x0c, 0x19, 0x92, 0x2d, 0x83, 0xb3, 0x65, 0x89, 0xb0, 0x75, 0x46, 0x48,
	0x36, 0x10, 0xc0, 0xf9, 0xfb, 0x23, 0x30, 0xce, 0xc6, 0xfb, 0x1e, 0xdc, 0xc7, 0xc1, 0xbf, 0xb0,
	0xa6, 0xaf, 0x84, 0xae, 0x7a, 0x3d, 0x5b, 0x87, 0xb5, 0xb0, 0x88, 0xbe, 0x36, 0x56, 0x7b, 0x5d,
	0x0d, 0x72, 0x44, 0xb7, 0x10, 0x16, 0x09, 0x2d, 0x52, 0xe8, 0xca, 0x3d, 0x14, 0x87, 0x70, 0x96,
	0x4a, 0xd0, 0x6f, 0x80, 0x41, 0x5a, 0xe7, 0x2f, 0x8a, 0x4f, 0xf8, 0x99, 0xfd, 0x64, 0x7f, 0xa4,
	0x25, 0x91, 0x1c, 0xf9, 0x84, 0xf4, 0x0b, 0xc8, 0xc8, 0xd7, 0xf6, 0x29, 0xb6, 0x45, 0x00, 0xa1,
	0x2c, 0xb7, 0xf0, 0x1a, 0xe7, 0xb4, 0x78, 0x9d, 0xd1, 0x79, 0xca, 0x60, 0x71, 0x48, 0x25, 0xe2,
	0xa4, 0x97, 0x86, 0xb2, 0x55, 0xca, 0x56, 0x63, 0xfb, 0xb8, 0x53, 0xfe, 0xc2, 0x5b, 0x7a, 0xef,
	0x8c, 0x56, 0x0e, 0xe9, 0x07, 0xe4, 0x16, 0xdd, 0x3c, 0xfa, 0xf4, 0x91, 0x94, 0x9a, 0xf7, 0x28,
	0xe2, 0xfe, 0x84, 0xf6, 0x26, 0x7b, 0xdc, 0x91, 0xf3, 0xb3, 0x08, 0xd9, 0x74, 0x5d, 0x1e, 0x97,
	0xdb, 0xdc, 0x03, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x54, 0x44, 0xf0, 0x0c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreatServiceClient is the client API for GreatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreatServiceClient interface {
}

type greatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreatServiceClient(cc grpc.ClientConnInterface) GreatServiceClient {
	return &greatServiceClient{cc}
}

// GreatServiceServer is the server API for GreatService service.
type GreatServiceServer interface {
}

// UnimplementedGreatServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreatServiceServer struct {
}

func RegisterGreatServiceServer(s *grpc.Server, srv GreatServiceServer) {
	s.RegisterService(&_GreatService_serviceDesc, srv)
}

var _GreatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greet.pb.GreatService",
	HandlerType: (*GreatServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "grpc-go-course/greet/proto-files/greet.proto",
}
