// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc-go-course/greet1/proto-files/greet.proto

package greetpb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	FirstNumber          int32    `protobuf:"varint,1,opt,name=first_number,json=firstNumber,proto3" json:"first_number,omitempty"`
	LastNumber           int32    `protobuf:"varint,2,opt,name=last_number,json=lastNumber,proto3" json:"last_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b63830541f3b23, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *Greeting) GetLastNumber() int32 {
	if m != nil {
		return m.LastNumber
	}
	return 0
}

type GreetRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b63830541f3b23, []int{1}
}

func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (m *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(m, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetResponse) Reset()         { *m = GreetResponse{} }
func (m *GreetResponse) String() string { return proto.CompactTextString(m) }
func (*GreetResponse) ProtoMessage()    {}
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b63830541f3b23, []int{2}
}

func (m *GreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetResponse.Unmarshal(m, b)
}
func (m *GreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetResponse.Marshal(b, m, deterministic)
}
func (m *GreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetResponse.Merge(m, src)
}
func (m *GreetResponse) XXX_Size() int {
	return xxx_messageInfo_GreetResponse.Size(m)
}
func (m *GreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetResponse proto.InternalMessageInfo

func (m *GreetResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type AverageRequest struct {
	Number               float32  `protobuf:"fixed32,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AverageRequest) Reset()         { *m = AverageRequest{} }
func (m *AverageRequest) String() string { return proto.CompactTextString(m) }
func (*AverageRequest) ProtoMessage()    {}
func (*AverageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b63830541f3b23, []int{3}
}

func (m *AverageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AverageRequest.Unmarshal(m, b)
}
func (m *AverageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AverageRequest.Marshal(b, m, deterministic)
}
func (m *AverageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AverageRequest.Merge(m, src)
}
func (m *AverageRequest) XXX_Size() int {
	return xxx_messageInfo_AverageRequest.Size(m)
}
func (m *AverageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AverageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AverageRequest proto.InternalMessageInfo

func (m *AverageRequest) GetNumber() float32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type AverageResponse struct {
	Average              float64  `protobuf:"fixed64,1,opt,name=average,proto3" json:"average,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AverageResponse) Reset()         { *m = AverageResponse{} }
func (m *AverageResponse) String() string { return proto.CompactTextString(m) }
func (*AverageResponse) ProtoMessage()    {}
func (*AverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b63830541f3b23, []int{4}
}

func (m *AverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AverageResponse.Unmarshal(m, b)
}
func (m *AverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AverageResponse.Marshal(b, m, deterministic)
}
func (m *AverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AverageResponse.Merge(m, src)
}
func (m *AverageResponse) XXX_Size() int {
	return xxx_messageInfo_AverageResponse.Size(m)
}
func (m *AverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AverageResponse proto.InternalMessageInfo

func (m *AverageResponse) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

type Greet1Request struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greet1Request) Reset()         { *m = Greet1Request{} }
func (m *Greet1Request) String() string { return proto.CompactTextString(m) }
func (*Greet1Request) ProtoMessage()    {}
func (*Greet1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b63830541f3b23, []int{5}
}

func (m *Greet1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greet1Request.Unmarshal(m, b)
}
func (m *Greet1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greet1Request.Marshal(b, m, deterministic)
}
func (m *Greet1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greet1Request.Merge(m, src)
}
func (m *Greet1Request) XXX_Size() int {
	return xxx_messageInfo_Greet1Request.Size(m)
}
func (m *Greet1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Greet1Request.DiscardUnknown(m)
}

var xxx_messageInfo_Greet1Request proto.InternalMessageInfo

func (m *Greet1Request) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Greet1Request) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type Greet1Response struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greet1Response) Reset()         { *m = Greet1Response{} }
func (m *Greet1Response) String() string { return proto.CompactTextString(m) }
func (*Greet1Response) ProtoMessage()    {}
func (*Greet1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b63830541f3b23, []int{6}
}

func (m *Greet1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greet1Response.Unmarshal(m, b)
}
func (m *Greet1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greet1Response.Marshal(b, m, deterministic)
}
func (m *Greet1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greet1Response.Merge(m, src)
}
func (m *Greet1Response) XXX_Size() int {
	return xxx_messageInfo_Greet1Response.Size(m)
}
func (m *Greet1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Greet1Response.DiscardUnknown(m)
}

var xxx_messageInfo_Greet1Response proto.InternalMessageInfo

func (m *Greet1Response) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type SquareRootRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SquareRootRequest) Reset()         { *m = SquareRootRequest{} }
func (m *SquareRootRequest) String() string { return proto.CompactTextString(m) }
func (*SquareRootRequest) ProtoMessage()    {}
func (*SquareRootRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b63830541f3b23, []int{7}
}

func (m *SquareRootRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SquareRootRequest.Unmarshal(m, b)
}
func (m *SquareRootRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SquareRootRequest.Marshal(b, m, deterministic)
}
func (m *SquareRootRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SquareRootRequest.Merge(m, src)
}
func (m *SquareRootRequest) XXX_Size() int {
	return xxx_messageInfo_SquareRootRequest.Size(m)
}
func (m *SquareRootRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SquareRootRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SquareRootRequest proto.InternalMessageInfo

func (m *SquareRootRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type SquareRootResponse struct {
	Number               float64  `protobuf:"fixed64,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SquareRootResponse) Reset()         { *m = SquareRootResponse{} }
func (m *SquareRootResponse) String() string { return proto.CompactTextString(m) }
func (*SquareRootResponse) ProtoMessage()    {}
func (*SquareRootResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b63830541f3b23, []int{8}
}

func (m *SquareRootResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SquareRootResponse.Unmarshal(m, b)
}
func (m *SquareRootResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SquareRootResponse.Marshal(b, m, deterministic)
}
func (m *SquareRootResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SquareRootResponse.Merge(m, src)
}
func (m *SquareRootResponse) XXX_Size() int {
	return xxx_messageInfo_SquareRootResponse.Size(m)
}
func (m *SquareRootResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SquareRootResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SquareRootResponse proto.InternalMessageInfo

func (m *SquareRootResponse) GetNumber() float64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type GreetWithDeadlineRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetWithDeadlineRequest) Reset()         { *m = GreetWithDeadlineRequest{} }
func (m *GreetWithDeadlineRequest) String() string { return proto.CompactTextString(m) }
func (*GreetWithDeadlineRequest) ProtoMessage()    {}
func (*GreetWithDeadlineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b63830541f3b23, []int{9}
}

func (m *GreetWithDeadlineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetWithDeadlineRequest.Unmarshal(m, b)
}
func (m *GreetWithDeadlineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetWithDeadlineRequest.Marshal(b, m, deterministic)
}
func (m *GreetWithDeadlineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetWithDeadlineRequest.Merge(m, src)
}
func (m *GreetWithDeadlineRequest) XXX_Size() int {
	return xxx_messageInfo_GreetWithDeadlineRequest.Size(m)
}
func (m *GreetWithDeadlineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetWithDeadlineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetWithDeadlineRequest proto.InternalMessageInfo

func (m *GreetWithDeadlineRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

type GreetWithDeadlineResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetWithDeadlineResponse) Reset()         { *m = GreetWithDeadlineResponse{} }
func (m *GreetWithDeadlineResponse) String() string { return proto.CompactTextString(m) }
func (*GreetWithDeadlineResponse) ProtoMessage()    {}
func (*GreetWithDeadlineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b63830541f3b23, []int{10}
}

func (m *GreetWithDeadlineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetWithDeadlineResponse.Unmarshal(m, b)
}
func (m *GreetWithDeadlineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetWithDeadlineResponse.Marshal(b, m, deterministic)
}
func (m *GreetWithDeadlineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetWithDeadlineResponse.Merge(m, src)
}
func (m *GreetWithDeadlineResponse) XXX_Size() int {
	return xxx_messageInfo_GreetWithDeadlineResponse.Size(m)
}
func (m *GreetWithDeadlineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetWithDeadlineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetWithDeadlineResponse proto.InternalMessageInfo

func (m *GreetWithDeadlineResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "Greeting")
	proto.RegisterType((*GreetRequest)(nil), "GreetRequest")
	proto.RegisterType((*GreetResponse)(nil), "GreetResponse")
	proto.RegisterType((*AverageRequest)(nil), "AverageRequest")
	proto.RegisterType((*AverageResponse)(nil), "AverageResponse")
	proto.RegisterType((*Greet1Request)(nil), "Greet1Request")
	proto.RegisterType((*Greet1Response)(nil), "Greet1Response")
	proto.RegisterType((*SquareRootRequest)(nil), "SquareRootRequest")
	proto.RegisterType((*SquareRootResponse)(nil), "SquareRootResponse")
	proto.RegisterType((*GreetWithDeadlineRequest)(nil), "GreetWithDeadlineRequest")
	proto.RegisterType((*GreetWithDeadlineResponse)(nil), "GreetWithDeadlineResponse")
}

func init() {
	proto.RegisterFile("grpc-go-course/greet1/proto-files/greet.proto", fileDescriptor_14b63830541f3b23)
}

var fileDescriptor_14b63830541f3b23 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5b, 0x6b, 0xd4, 0x40,
	0x14, 0x6e, 0x02, 0xdd, 0x6e, 0xce, 0x76, 0x1b, 0x3b, 0x4a, 0xd9, 0x46, 0x44, 0x1d, 0x10, 0x17,
	0x6a, 0xa6, 0x37, 0x2a, 0xf6, 0xd1, 0x2a, 0x08, 0x0a, 0x7d, 0xc8, 0x22, 0x82, 0x2f, 0x32, 0xbb,
	0x3d, 0x8d, 0x03, 0xb9, 0xed, 0x64, 0xb2, 0xe0, 0x8f, 0xf6, 0x3f, 0x48, 0x26, 0x93, 0xcb, 0xba,
	0x59, 0xed, 0xe3, 0x39, 0xf3, 0x7d, 0xdf, 0xb9, 0x7c, 0x67, 0xc0, 0x0f, 0x65, 0xb6, 0xf0, 0xc3,
	0xd4, 0x5f, 0xa4, 0x85, 0xcc, 0xf1, 0x34, 0x94, 0x88, 0xea, 0xfc, 0x34, 0x93, 0xa9, 0x4a, 0xfd,
	0x7b, 0x11, 0x61, 0x5e, 0xa5, 0x98, 0xce, 0xd0, 0x5b, 0x18, 0x7e, 0x2a, 0x43, 0x91, 0x84, 0xe4,
	0x25, 0xec, 0xdf, 0x0b, 0x99, 0xab, 0x1f, 0x49, 0x11, 0xcf, 0x51, 0x4e, 0xac, 0x17, 0xd6, 0x74,
	0x37, 0x18, 0xe9, 0xdc, 0xad, 0x4e, 0x91, 0xe7, 0x30, 0x8a, 0x78, 0x8b, 0xb0, 0x35, 0x02, 0xca,
	0x54, 0x05, 0xa0, 0x57, 0xb0, 0xaf, 0xf5, 0x02, 0x5c, 0x16, 0x98, 0x2b, 0xf2, 0x0a, 0x86, 0xa1,
	0xd1, 0xd7, 0x7a, 0xa3, 0x0b, 0x87, 0xd5, 0x05, 0x83, 0xe6, 0x89, 0xbe, 0x86, 0xb1, 0xa1, 0xe5,
	0x59, 0x9a, 0xe4, 0x48, 0x8e, 0x60, 0x20, 0x31, 0x2f, 0x22, 0x65, 0xba, 0x30, 0x11, 0x9d, 0xc2,
	0xc1, 0xfb, 0x15, 0x4a, 0x1e, 0x62, 0x5d, 0xe1, 0x08, 0x06, 0x9d, 0x7e, 0xed, 0xc0, 0x44, 0xf4,
	0x04, 0xdc, 0x06, 0x69, 0x44, 0x27, 0xb0, 0xc7, 0xab, 0x94, 0xc6, 0x5a, 0x41, 0x1d, 0xd2, 0x2f,
	0xa6, 0xfe, 0x79, 0xad, 0xfa, 0x0c, 0xc0, 0xec, 0x82, 0xc7, 0x15, 0xda, 0x09, 0x9c, 0x6a, 0x13,
	0x3c, 0x46, 0xf2, 0x14, 0x9c, 0x6a, 0x0f, 0xe5, 0xab, 0xad, 0x5f, 0x87, 0x7a, 0x0b, 0x3c, 0xc6,
	0xb2, 0xc7, 0x5a, 0xac, 0x77, 0x1a, 0xa7, 0x99, 0xe6, 0x04, 0x0e, 0x67, 0xcb, 0x82, 0x4b, 0x0c,
	0xd2, 0x54, 0xf5, 0x0f, 0xb4, 0xdb, 0x0c, 0xf4, 0x06, 0x48, 0x17, 0xdc, 0x4a, 0x77, 0xd0, 0x56,
	0x83, 0xbe, 0x86, 0x89, 0x6e, 0xe2, 0x9b, 0x50, 0x3f, 0x3f, 0x22, 0xbf, 0x8b, 0x44, 0x82, 0x0f,
	0x1b, 0x8e, 0x5e, 0xc2, 0x71, 0x0f, 0xf5, 0xdf, 0xa3, 0x5c, 0xfc, 0xb6, 0x8d, 0xf3, 0x33, 0x94,
	0x2b, 0xb1, 0x40, 0xe2, 0x03, 0xe8, 0xf8, 0x6b, 0xc2, 0xe5, 0x2f, 0x32, 0x66, 0xdd, 0xb3, 0xf0,
	0x0e, 0xd8, 0x9a, 0xdd, 0x74, 0x87, 0x5c, 0xc3, 0x93, 0x86, 0x8e, 0x72, 0xa6, 0x24, 0xf2, 0xb8,
	0x3c, 0xca, 0xff, 0x11, 0xcf, 0x2c, 0xf2, 0x0e, 0xdc, 0x0f, 0x91, 0xc0, 0x44, 0xb5, 0x2c, 0x97,
	0xad, 0x5f, 0x89, 0xf7, 0x88, 0xfd, 0x75, 0x0c, 0x74, 0x67, 0x6a, 0x91, 0xb7, 0x30, 0xbe, 0x11,
	0x77, 0xd8, 0xf2, 0x8c, 0x7c, 0x7d, 0x06, 0x9e, 0xcb, 0xd6, 0x9d, 0x2c, 0x59, 0x67, 0x16, 0xb9,
	0x02, 0x68, 0xad, 0x20, 0x84, 0x6d, 0x98, 0xe8, 0x3d, 0x66, 0x3d, 0x5e, 0x7d, 0x86, 0xc3, 0x8d,
	0xc5, 0x92, 0x63, 0xb6, 0xcd, 0x27, 0xcf, 0x63, 0x5b, 0x7d, 0xb8, 0x71, 0xbe, 0xef, 0xe9, 0xdf,
	0x93, 0xcd, 0xe7, 0x03, 0xfd, 0x95, 0x2f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x6f, 0xc0,
	0x9c, 0xfb, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreetServiceClient is the client API for GreetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetServiceClient interface {
	GreetUnary(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
	GreetServerStreaming(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (GreetService_GreetServerStreamingClient, error)
	ClientStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetService_ClientStreamingClient, error)
	BideStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetService_BideStreamingClient, error)
	SquareRoot(ctx context.Context, in *SquareRootRequest, opts ...grpc.CallOption) (*SquareRootResponse, error)
	GreetWithDeadline(ctx context.Context, in *GreetWithDeadlineRequest, opts ...grpc.CallOption) (*GreetWithDeadlineResponse, error)
}

type greetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetServiceClient(cc grpc.ClientConnInterface) GreetServiceClient {
	return &greetServiceClient{cc}
}

func (c *greetServiceClient) GreetUnary(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, "/GreetService/GreetUnary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) GreetServerStreaming(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (GreetService_GreetServerStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[0], "/GreetService/GreetServerStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceGreetServerStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreetService_GreetServerStreamingClient interface {
	Recv() (*GreetResponse, error)
	grpc.ClientStream
}

type greetServiceGreetServerStreamingClient struct {
	grpc.ClientStream
}

func (x *greetServiceGreetServerStreamingClient) Recv() (*GreetResponse, error) {
	m := new(GreetResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) ClientStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetService_ClientStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[1], "/GreetService/ClientStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceClientStreamingClient{stream}
	return x, nil
}

type GreetService_ClientStreamingClient interface {
	Send(*AverageRequest) error
	CloseAndRecv() (*AverageResponse, error)
	grpc.ClientStream
}

type greetServiceClientStreamingClient struct {
	grpc.ClientStream
}

func (x *greetServiceClientStreamingClient) Send(m *AverageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceClientStreamingClient) CloseAndRecv() (*AverageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AverageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) BideStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetService_BideStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[2], "/GreetService/BideStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceBideStreamingClient{stream}
	return x, nil
}

type GreetService_BideStreamingClient interface {
	Send(*Greet1Request) error
	Recv() (*Greet1Response, error)
	grpc.ClientStream
}

type greetServiceBideStreamingClient struct {
	grpc.ClientStream
}

func (x *greetServiceBideStreamingClient) Send(m *Greet1Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceBideStreamingClient) Recv() (*Greet1Response, error) {
	m := new(Greet1Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) SquareRoot(ctx context.Context, in *SquareRootRequest, opts ...grpc.CallOption) (*SquareRootResponse, error) {
	out := new(SquareRootResponse)
	err := c.cc.Invoke(ctx, "/GreetService/SquareRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) GreetWithDeadline(ctx context.Context, in *GreetWithDeadlineRequest, opts ...grpc.CallOption) (*GreetWithDeadlineResponse, error) {
	out := new(GreetWithDeadlineResponse)
	err := c.cc.Invoke(ctx, "/GreetService/GreetWithDeadline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetServiceServer is the server API for GreetService service.
type GreetServiceServer interface {
	GreetUnary(context.Context, *GreetRequest) (*GreetResponse, error)
	GreetServerStreaming(*GreetRequest, GreetService_GreetServerStreamingServer) error
	ClientStreaming(GreetService_ClientStreamingServer) error
	BideStreaming(GreetService_BideStreamingServer) error
	SquareRoot(context.Context, *SquareRootRequest) (*SquareRootResponse, error)
	GreetWithDeadline(context.Context, *GreetWithDeadlineRequest) (*GreetWithDeadlineResponse, error)
}

// UnimplementedGreetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetServiceServer struct {
}

func (*UnimplementedGreetServiceServer) GreetUnary(ctx context.Context, req *GreetRequest) (*GreetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GreetUnary not implemented")
}
func (*UnimplementedGreetServiceServer) GreetServerStreaming(req *GreetRequest, srv GreetService_GreetServerStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetServerStreaming not implemented")
}
func (*UnimplementedGreetServiceServer) ClientStreaming(srv GreetService_ClientStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreaming not implemented")
}
func (*UnimplementedGreetServiceServer) BideStreaming(srv GreetService_BideStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method BideStreaming not implemented")
}
func (*UnimplementedGreetServiceServer) SquareRoot(ctx context.Context, req *SquareRootRequest) (*SquareRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SquareRoot not implemented")
}
func (*UnimplementedGreetServiceServer) GreetWithDeadline(ctx context.Context, req *GreetWithDeadlineRequest) (*GreetWithDeadlineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GreetWithDeadline not implemented")
}

func RegisterGreetServiceServer(s *grpc.Server, srv GreetServiceServer) {
	s.RegisterService(&_GreetService_serviceDesc, srv)
}

func _GreetService_GreetUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).GreetUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GreetService/GreetUnary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).GreetUnary(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_GreetServerStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GreetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetServiceServer).GreetServerStreaming(m, &greetServiceGreetServerStreamingServer{stream})
}

type GreetService_GreetServerStreamingServer interface {
	Send(*GreetResponse) error
	grpc.ServerStream
}

type greetServiceGreetServerStreamingServer struct {
	grpc.ServerStream
}

func (x *greetServiceGreetServerStreamingServer) Send(m *GreetResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GreetService_ClientStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).ClientStreaming(&greetServiceClientStreamingServer{stream})
}

type GreetService_ClientStreamingServer interface {
	SendAndClose(*AverageResponse) error
	Recv() (*AverageRequest, error)
	grpc.ServerStream
}

type greetServiceClientStreamingServer struct {
	grpc.ServerStream
}

func (x *greetServiceClientStreamingServer) SendAndClose(m *AverageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceClientStreamingServer) Recv() (*AverageRequest, error) {
	m := new(AverageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetService_BideStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).BideStreaming(&greetServiceBideStreamingServer{stream})
}

type GreetService_BideStreamingServer interface {
	Send(*Greet1Response) error
	Recv() (*Greet1Request, error)
	grpc.ServerStream
}

type greetServiceBideStreamingServer struct {
	grpc.ServerStream
}

func (x *greetServiceBideStreamingServer) Send(m *Greet1Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceBideStreamingServer) Recv() (*Greet1Request, error) {
	m := new(Greet1Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetService_SquareRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SquareRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).SquareRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GreetService/SquareRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).SquareRoot(ctx, req.(*SquareRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_GreetWithDeadline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetWithDeadlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).GreetWithDeadline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GreetService/GreetWithDeadline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).GreetWithDeadline(ctx, req.(*GreetWithDeadlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GreetService",
	HandlerType: (*GreetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GreetUnary",
			Handler:    _GreetService_GreetUnary_Handler,
		},
		{
			MethodName: "SquareRoot",
			Handler:    _GreetService_SquareRoot_Handler,
		},
		{
			MethodName: "GreetWithDeadline",
			Handler:    _GreetService_GreetWithDeadline_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GreetServerStreaming",
			Handler:       _GreetService_GreetServerStreaming_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStreaming",
			Handler:       _GreetService_ClientStreaming_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BideStreaming",
			Handler:       _GreetService_BideStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc-go-course/greet1/proto-files/greet.proto",
}
